tilted: tilted.o model.o events.o raster.o rast_asm.o renderer.o
	cc68x -g tilted.o model.o events.o raster.o rast_asm.o renderer.o -o tilted
	
tilted.o: tilted.c
	cc68x -g -c tilted.c
	
renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c
	
model.o: model.c model.h
	cc68x -g -c model.c
	
events.o: events.c events.h
	cc68x -g -c events.c

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
