tst_mod: tst_mod.o model.o event.o
	cc68x -g tst_mod.o model.o event.o -o tst_mod

tst_rast: tst_rast.o raster.o rast_asm.o
	cc68x -g tst_rast.o raster.o rast_asm.o -o tst_rast
	
tst_mod.o: tst_mod.c model.h event.h
	cc68x -g -c tst_mod.c
	
model.o: model.c model.h
	cc68x -g -c model.c
	
event.o: event.c event.h
	cc68x -g -c event.c

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
