tiltedTowerz: tiltedTowerz.o model.o event.o raster.o rast_asm.o renderer.o
	cc68x -g tiltedTowerz.o model.o event.o raster.o rast_asm.o renderer.o -o tiltedTowerz
	
tiltedTowerz.o: tiltedTowerz.c tiltedTowerz.h
	cc68x -g -c tiltedTowerz.c
	
renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c
	
model.o: model.c model.h
	cc68x -g -c model.c
	
event.o: event.c event.h
	cc68x -g -c event.c

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
